#!/usr/bin/env bash

    count="$(dunstctl count history 2>/dev/null || echo 0)"

    if [ "${count:-0}" -gt 0 ]; then
        col="#0f0f17"
        bg="#bbc5d7"
        icon=""
    else
        bg="#0f0f17"
        col="#bbc5d7"
        icon=""
    fi



    if [ "$(dunstctl is-paused 2>/dev/null || echo false)" == "true" ]; then
        icon=""
        col="#d78787"
        bg="#0f0f17"
    fi


if [ $1 = "notifs" ]; then
    echo $icon
elif [ $1 = "notifs_col" ]; then
    echo $col
elif [ $1 = "notifs_bg" ]; then
    echo $bg
elif [ $1 = "toggle_notifs" ]; then
    dunstctl set-paused toggle 2>/dev/null || true
fi
