#!/usr/bin/env bash

    cmd="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null | awk '{print $3}')"


    if [ "$cmd" != "[MUTED]" ] && [ -n "$cmd" ]; then
        col="#0f0f17"
        bg="#bbc5d7"
        icon=""
    else
        bg="#0f0f17"
        col="#bbc5d7"
        icon=""
    fi



if [ "$1" = "vol" ]; then
    echo $icon
elif [ "$1" = "vol_col" ]; then
    echo $col
elif [ "$1" = "vol_bg" ]; then
    echo $bg
fi
