{ pkgs, ... }:

{
  # Bootloader. Keep only the latest generations in the boot menu; older ones
  # are removed from /boot on the next switch (and from the store by nix.gc).
  boot.loader.systemd-boot = {
    enable = true;
    configurationLimit = 5;
  };
  boot.loader.efi.canTouchEfiVariables = true;

  # Wine/Proton use /dev/ntsync (kernel 6.14+) for faster thread synchronisation.
  boot.kernelModules = [ "ntsync" ];

  # Common removable-drive formats. vfat covers FAT32 and is already used by
  # the EFI partition; enable NTFS and exFAT for external storage as well.
  boot.supportedFilesystems = [ "ntfs" "vfat" "exfat" ];

  # Intel laptop panel: PSR2 selective fetch fails ("Selective fetch area calculation
  # failed in pipe A" in dmesg) and causes black flicker when only part of the screen
  # updates (e.g. rotating a 3D view). Panel Self Refresh off fixes it.
  # quiet/splash/loglevel: no kernel or initrd text between the boot menu and the desktop.
  # Keep the supported Iris Xe and Arc devices on i915; do not force-probe them with xe.
  boot.kernelParams = [ "i915.enable_psr=0" "xe.force_probe=!*" "consoleblank=0" "quiet" "splash" "loglevel=3" "udev.log_level=3" "rd.systemd.show_status=false"
  ];
  boot.consoleLogLevel = 0;
  boot.initrd.verbose = false;

  # Graphical boot splash (hands over to SDDM/autologin without a text console).
  boot.plymouth = {
    enable = true;
    theme = "catppuccin-mocha";
    themePackages = [ (pkgs.catppuccin-plymouth.override { variant = "mocha"; }) ];
  };

  networking.hostName = "linux";

  # Shutdown used to wait for the full stop timeout on "User Manager for UID 1000".
  # user@.service ships its own long TimeoutStopSec, so it is overridden separately
  # from the global default. Stuck user processes (e.g. Wine) get killed after 15s.
  systemd.settings.Manager.DefaultTimeoutStopSec = "15s";
  systemd.services."user@" = {
    overrideStrategy = "asDropin";
    serviceConfig.TimeoutStopSec = "15s";
  };
  networking.networkmanager.enable = true;

  time.timeZone = "Asia/Seoul";

  i18n.defaultLocale = "en_US.UTF-8";
  # Korean locale for apps that ask for it (Hancom, previously generated by the hnc module).
  i18n.extraLocales = [ "ko_KR.UTF-8/UTF-8" ];
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  users.users."linux" = {
    isNormalUser = true;
    description = "Linux";
    extraGroups = [ "networkmanager" "wheel" ];
  };

  services.openssh.enable = true;

  nixpkgs.config.allowUnfree = true;

  nix.settings = {
    extra-substituters = [ "https://noctalia.cachix.org" ];
    extra-trusted-public-keys = [ "noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=" ];
  };

  # Automatic cleanup of old build results: every week, delete generations and
  # store paths older than 7 days (the running generation is always kept),
  # and hard-link identical files in the store.
  nix.gc = {
    automatic = true;
    dates = "weekly";
    persistent = true;
    options = "--delete-older-than 7d";
  };
  nix.optimise.automatic = true;

  # Do not change after install; see `man configuration.nix`.
  system.stateVersion = "26.05";
}
