#!/usr/bin/env bash

battery() {
	BAT=$(ls /sys/class/power_supply 2>/dev/null | grep BAT | head -n 1)
	cat /sys/class/power_supply/${BAT}/capacity 2>/dev/null || echo 100
}
battery_stat() {
	BAT=$(ls /sys/class/power_supply 2>/dev/null | grep BAT | head -n 1)
	cat /sys/class/power_supply/${BAT}/status 2>/dev/null || echo Unknown
}

if [ "$1" = "--bat" ]; then
	battery
elif [ "$1" = "--bat-st" ]; then
	battery_stat
fi

